In [1]:
import torch

## 验证4

U = X W

V = A B

Y = U + V

Z = sigmoid(Y)

l = MS(Z)

In [2]:
X = torch.tensor(
    [
        [-0.4902, -1.2284, 0.4850, -0.7626, 0.5833, -0.2165, 0.0250, 1.3206, -0.6927, -0.6556, -0.3341, 2.2979],
        [0.5040, 0.6535, -1.2604, 0.8739, -0.4709, -0.3864, 0.2225, 0.3425, 0.4238, 0.3726, -0.1357, -1.8972],
        [-0.5126, -1.6717, -0.1513, -0.4067, 1.8788, -1.1897, 2.0210, -1.4236, -0.0539, -0.4232, 0.4262, -1.5843],
        [1.2996, -0.9194, 0.0749, -0.8276, 0.4064, -0.7230, 0.8784, 0.9496, 1.8156, 1.1740, 0.0550, -0.5953],
        [0.1478, 1.9026, -0.0345, 0.4228, 0.3500, -1.2957, 0.0657, -0.9554, 0.1479, 0.6662, -0.4103, -0.1112],
        [0.5418, -0.6957, 0.4078, 0.1623, -0.0968, -1.2848, 0.6739, -0.7713, -0.6456, -0.2052, 1.0688, -0.2967],
        [-0.8826, -0.8036, 0.5668, -0.5170, -0.3979, 0.5788, -0.1583, 0.3667, 0.7867, -1.1279, 1.5490, 1.8143],
        [0.1602, -0.2151, 1.1715, -1.0736, 1.5675, -0.5197, -1.3860, -0.5850, 0.1505, -0.3224, 0.9491, 0.3462],
        [-0.2498, 0.8156, 0.3079, -0.2045, -1.1184, -1.4312, 0.0642, 1.5597, 0.2400, -0.1181, -0.7843, 1.1014],
        [0.9969, 0.5992, -0.1434, 0.6869, 0.3702, -1.5449, 1.5708, 1.0349, 0.6319, -1.2005, 0.7468, -0.0538]
    ]
    , dtype=torch.float32)
W = torch.tensor(
    [
        [0.8826, 0.7571],
        [0.3064, -2.5688],
        [-0.1909, 0.9261],
        [-0.4558, 0.5120],
        [1.3289, -1.3281],
        [-0.4361, -1.2097],
        [-0.1454, 0.3818],
        [-1.4087, 0.0254],
        [0.9254, -0.9061],
        [-1.1026, 1.1963],
        [-0.0287, -0.7889],
        [1.6940, -0.2290]
    ]
    , dtype=torch.float32)
A = torch.tensor(
    [
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000]
    ]
    , dtype=torch.float32)
B = torch.tensor(
    [
        [0.9256, 0.2128]
    ]
    , dtype=torch.float32)

X.requires_grad_(requires_grad=True)
W.requires_grad_(requires_grad=True)
B.requires_grad_(requires_grad=True)

tensor([[0.9256, 0.2128]], requires_grad=True)

In [3]:
U=torch.mm(X, W)
U

tensor([[ 2.4356,  1.9541],
        [-3.7134, -0.2272],
        [ 1.6975,  2.8064],
        [-0.0061,  3.5380],
        [ 2.1195, -2.4755],
        [ 0.6289,  4.1428],
        [ 2.8281, -2.2662],
        [ 4.7305, -2.1382],
        [-0.7641,  1.1848],
        [ 2.0530, -1.1479]], grad_fn=<MmBackward>)

In [4]:
V=torch.mm(A, B)
V

tensor([[0.9256, 0.2128],
        [0.9256, 0.2128],
        [0.9256, 0.2128],
        [0.9256, 0.2128],
        [0.9256, 0.2128],
        [0.9256, 0.2128],
        [0.9256, 0.2128],
        [0.9256, 0.2128],
        [0.9256, 0.2128],
        [0.9256, 0.2128]], grad_fn=<MmBackward>)

In [5]:
Y = U + V
Y

tensor([[ 3.3612,  2.1669],
        [-2.7878, -0.0144],
        [ 2.6231,  3.0192],
        [ 0.9195,  3.7508],
        [ 3.0451, -2.2627],
        [ 1.5545,  4.3556],
        [ 3.7537, -2.0534],
        [ 5.6561, -1.9254],
        [ 0.1615,  1.3976],
        [ 2.9786, -0.9351]], grad_fn=<AddBackward0>)

In [6]:
Z=torch.sigmoid(Y)
Z

tensor([[0.9665, 0.8972],
        [0.0580, 0.4964],
        [0.9323, 0.9534],
        [0.7149, 0.9770],
        [0.9546, 0.0943],
        [0.8256, 0.9873],
        [0.9771, 0.1137],
        [0.9965, 0.1273],
        [0.5403, 0.8018],
        [0.9516, 0.2819]], grad_fn=<SigmoidBackward>)

In [7]:
r,c=Z.shape
l=(Z**2).sum()/r
l

tensor(1.1706, grad_fn=<DivBackward0>)

In [8]:
l.backward()

In [9]:
X.grad

tensor([[ 1.8055e-02, -4.0582e-02,  1.4127e-02,  5.6162e-03, -1.3650e-02,
         -2.2746e-02,  5.4063e-03, -8.4033e-03, -9.1954e-03,  1.2887e-02,
         -1.3232e-02,  6.8217e-03],
        [ 1.9349e-02, -6.3559e-02,  2.2863e-02,  1.2418e-02, -3.2119e-02,
         -3.0299e-02,  9.3836e-03, -2.6210e-04, -2.1902e-02,  2.8992e-02,
         -1.9597e-02, -4.6102e-03],
        [ 1.6793e-02, -1.8144e-02,  5.5949e-03, -1.0273e-03,  4.3892e-03,
         -1.5372e-02,  1.5219e-03, -1.6357e-02,  3.2152e-03, -2.8428e-03,
         -7.0167e-03,  1.7990e-02],
        [ 2.9039e-02, -2.3318e-03, -1.5034e-03, -1.1038e-02,  3.2904e-02,
         -1.8011e-02, -2.5635e-03, -4.0940e-02,  2.2995e-02, -2.6887e-02,
         -4.2946e-03,  4.8361e-02],
        [ 8.5258e-03, -1.5979e-03, -8.9897e-05, -2.9496e-03,  8.8646e-03,
         -5.5576e-03, -5.8927e-04, -1.1622e-02,  6.2032e-03, -7.2032e-03,
         -1.5074e-03,  1.3656e-02],
        [ 2.2856e-02,  9.3903e-04, -2.2511e-03, -9.5727e-03,  2.8316e-02,
      

In [10]:
W.grad

tensor([[ 0.0415,  0.0108],
        [-0.0310,  0.0042],
        [ 0.0223, -0.0124],
        [-0.0282,  0.0015],
        [ 0.0105, -0.0048],
        [-0.1277, -0.0859],
        [ 0.0801,  0.0439],
        [ 0.0453,  0.0698],
        [ 0.0496,  0.0208],
        [ 0.0072, -0.0197],
        [ 0.0194, -0.0083],
        [ 0.0065,  0.0066]])

In [11]:
B.grad

tensor([[0.1205, 0.1003]])