In [1]:
import torch

## 验证1

Y = X W

Z = Y + B

l = MS(Z)

In [2]:
X = torch.tensor([[4,2,3],[1,4,3],[1,2,5]], dtype=torch.float32)
W = torch.tensor([[3,2,5],[1,9,3],[7,2,1]], dtype=torch.float32)
B = torch.tensor([[1,0,1],[0,1,0],[1,0,1]], dtype=torch.float32)

X.requires_grad_(requires_grad=True)
W.requires_grad_(requires_grad=True)
B.requires_grad_(requires_grad=True)

tensor([[1., 0., 1.],
        [0., 1., 0.],
        [1., 0., 1.]], requires_grad=True)

In [3]:
Y=torch.mm(X, W)
Y

tensor([[35., 32., 29.],
        [28., 44., 20.],
        [40., 30., 16.]], grad_fn=<MmBackward>)

In [4]:
Z=Y+B
Z

tensor([[36., 32., 30.],
        [28., 45., 20.],
        [41., 30., 17.]], grad_fn=<AddBackward0>)

In [5]:
l=(Z**2).sum()/3
l

tensor(3099.6667, grad_fn=<DivBackward0>)

In [6]:
l.backward()

In [7]:
X.grad

tensor([[214.6667, 276.0000, 230.6667],
        [182.6667, 328.6667, 204.0000],
        [178.6667, 241.3333, 242.6667]])

In [8]:
W.grad

tensor([[142.0000, 135.3333, 104.6667],
        [177.3333, 202.6667, 116.0000],
        [264.6667, 254.0000, 156.6667]])

In [9]:
B.grad

tensor([[24.0000, 21.3333, 20.0000],
        [18.6667, 30.0000, 13.3333],
        [27.3333, 20.0000, 11.3333]])

## 验证2

Y = X W

Z = Y + B

U = Sigmoid(Z)

l = MS(U)

In [10]:
X = torch.tensor([[0.4,0.2,0.3],[0.1,0.4,0.3],[0.1,0.2,0.5],[0.3,0.6,0.3],[0.8,0.6,0.5]], dtype=torch.float32)
W = torch.tensor([[3,2,5,1],[1,5,9,3],[4,7,2,1]], dtype=torch.float32)
B = torch.tensor([[-1,0,1,-2],[-3,0,-1,0],[1,2,0,-1],[3,-2,1,2],[-3,2,-1,1]], dtype=torch.float32)

X.requires_grad_(requires_grad=True)
W.requires_grad_(requires_grad=True)
B.requires_grad_(requires_grad=True)

tensor([[-1.,  0.,  1., -2.],
        [-3.,  0., -1.,  0.],
        [ 1.,  2.,  0., -1.],
        [ 3., -2.,  1.,  2.],
        [-3.,  2., -1.,  1.]], requires_grad=True)

In [11]:
Y=torch.mm(X, W)
Y

tensor([[ 2.6000,  3.9000,  4.4000,  1.3000],
        [ 1.9000,  4.3000,  4.7000,  1.6000],
        [ 2.5000,  4.7000,  3.3000,  1.2000],
        [ 2.7000,  5.7000,  7.5000,  2.4000],
        [ 5.0000,  8.1000, 10.4000,  3.1000]], grad_fn=<MmBackward>)

In [12]:
Z=Y+B
Z

tensor([[ 1.6000,  3.9000,  5.4000, -0.7000],
        [-1.1000,  4.3000,  3.7000,  1.6000],
        [ 3.5000,  6.7000,  3.3000,  0.2000],
        [ 5.7000,  3.7000,  8.5000,  4.4000],
        [ 2.0000, 10.1000,  9.4000,  4.1000]], grad_fn=<AddBackward0>)

In [13]:
U=torch.sigmoid(Z)
U

tensor([[0.8320, 0.9802, 0.9955, 0.3318],
        [0.2497, 0.9866, 0.9759, 0.8320],
        [0.9707, 0.9988, 0.9644, 0.5498],
        [0.9967, 0.9759, 0.9998, 0.9879],
        [0.8808, 1.0000, 0.9999, 0.9837]], grad_fn=<SigmoidBackward>)

In [14]:
r,c=U.shape
l=(U**2).sum()/r
l

tensor(3.2542, grad_fn=<DivBackward0>)

In [15]:
l.backward()

In [16]:
X.grad

tensor([[0.1931, 0.1890, 0.2724],
        [0.1590, 0.2670, 0.1763],
        [0.1547, 0.2959, 0.1285],
        [0.0275, 0.0622, 0.0745],
        [0.1175, 0.0563, 0.1545]])

In [17]:
W.grad

tensor([[0.0516, 0.0064, 0.0030, 0.0283],
        [0.0420, 0.0092, 0.0067, 0.0420],
        [0.0440, 0.0069, 0.0099, 0.0546]])

In [18]:
B.grad

tensor([[4.6514e-02, 7.6243e-03, 1.7824e-03, 2.9427e-02],
        [1.8717e-02, 5.2124e-03, 9.1907e-03, 4.6514e-02],
        [1.1048e-02, 4.9058e-04, 1.3234e-02, 5.4437e-02],
        [1.3250e-03, 9.1907e-03, 8.1339e-05, 4.7344e-03],
        [3.6991e-02, 1.6450e-05, 3.3087e-05, 6.3101e-03]])

## 验证3

Y = X W

Z = Y + B

U = Sigmoid(Z)

V = U + B

l = MS(V)

In [19]:
X = torch.tensor([[0.4,0.2,0.3],[0.1,0.4,0.3],[0.1,0.2,0.5],[0.3,0.6,0.3],[0.8,0.6,0.5]], dtype=torch.float32)
W = torch.tensor([[3,2,5,1],[1,5,9,3],[4,7,2,1]], dtype=torch.float32)
B = torch.tensor([[-1,0,1,-2],[-3,0,-1,0],[1,2,0,-1],[3,-2,1,2],[-3,2,-1,1]], dtype=torch.float32)

X.requires_grad_(requires_grad=True)
W.requires_grad_(requires_grad=True)
B.requires_grad_(requires_grad=True)

tensor([[-1.,  0.,  1., -2.],
        [-3.,  0., -1.,  0.],
        [ 1.,  2.,  0., -1.],
        [ 3., -2.,  1.,  2.],
        [-3.,  2., -1.,  1.]], requires_grad=True)

In [20]:
Y=torch.mm(X, W)
Y

tensor([[ 2.6000,  3.9000,  4.4000,  1.3000],
        [ 1.9000,  4.3000,  4.7000,  1.6000],
        [ 2.5000,  4.7000,  3.3000,  1.2000],
        [ 2.7000,  5.7000,  7.5000,  2.4000],
        [ 5.0000,  8.1000, 10.4000,  3.1000]], grad_fn=<MmBackward>)

In [21]:
Z=Y+B
Z

tensor([[ 1.6000,  3.9000,  5.4000, -0.7000],
        [-1.1000,  4.3000,  3.7000,  1.6000],
        [ 3.5000,  6.7000,  3.3000,  0.2000],
        [ 5.7000,  3.7000,  8.5000,  4.4000],
        [ 2.0000, 10.1000,  9.4000,  4.1000]], grad_fn=<AddBackward0>)

In [22]:
U=torch.sigmoid(Z)
U

tensor([[0.8320, 0.9802, 0.9955, 0.3318],
        [0.2497, 0.9866, 0.9759, 0.8320],
        [0.9707, 0.9988, 0.9644, 0.5498],
        [0.9967, 0.9759, 0.9998, 0.9879],
        [0.8808, 1.0000, 0.9999, 0.9837]], grad_fn=<SigmoidBackward>)

In [23]:
V = U + B
V

tensor([[-1.6798e-01,  9.8016e-01,  1.9955e+00, -1.6682e+00],
        [-2.7503e+00,  9.8661e-01, -2.4127e-02,  8.3202e-01],
        [ 1.9707e+00,  2.9988e+00,  9.6443e-01, -4.5017e-01],
        [ 3.9967e+00, -1.0241e+00,  1.9998e+00,  2.9879e+00],
        [-2.1192e+00,  3.0000e+00, -8.2731e-05,  1.9837e+00]],
       grad_fn=<AddBackward0>)

In [24]:
r,c=V.shape

l=(V**2).sum()/r
l

tensor(15.6735, grad_fn=<DivBackward0>)

In [25]:
l.backward()

In [26]:
X.grad

tensor([[-0.1430, -0.3829, -0.1250],
        [-0.5626, -0.0426, -0.7420],
        [ 0.0918,  0.0152,  0.0819],
        [ 0.0118,  0.0015, -0.0316],
        [-0.2542, -0.0506, -0.3429]])

In [27]:
W.grad

tensor([[-0.0917,  0.0009,  0.0028, -0.0445],
        [-0.1301, -0.0019,  0.0034, -0.0037],
        [-0.0963,  0.0017,  0.0077, -0.0421]])

In [28]:
B.grad

tensor([[-7.6584e-02,  3.9969e-01,  8.0177e-01, -8.1522e-01],
        [-1.3062e+00,  3.9986e-01, -9.8780e-03,  3.7932e-01],
        [ 8.1070e-01,  1.2010e+00,  3.9901e-01, -2.2464e-01],
        [ 1.6040e+00, -4.1930e-01,  8.0008e-01,  1.2095e+00],
        [-9.3668e-01,  1.2000e+00, -3.3095e-05,  8.0620e-01]])